force-app/main/default/objects/Insurance_Policy__c/Insurance_Policy__c.object-meta.xml
<CustomObject>
    <label>Insurance Policy</label>
    <nameField>
        <label>Insurance Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insurance Policies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insurance_Policy__c/fields/Issuing_Date__c.field-meta.xml
<CustomField>
    <fullName>Issuing_Date__c</fullName>
    <label>Issuing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insurance_Policy__c/fields/Premium__c.field-meta.xml
<CustomField>
    <fullName>Premium__c</fullName>
    <label>Premium</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Insurance_Policy__c/fields/Premium_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Premium_Frequency__c</fullName>
    <label>Premium Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Policy__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Issued</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PolicyBulkUpdate.cls
public class PolicyBulkUpdate implements Database.Batchable<sObject>,Database.Stateful{
    public static List<string> policyIds = new List<string>();
    public Database.QueryLocator start(Database.BatchableContext BC){
      	string query = 'select Id,Effective_Date__c,Contact_Email__c,Name,Expiration_Date__c,Issuing_Date__c,Premium__c,Premium_Frequency__c,Status__c from Insurance_Policy__c';     
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext BC, List<sObject> scope){
        List<Insurance_Policy__c> ips = new List<Insurance_Policy__c>();
        for(sObject sc : scope){
            Insurance_Policy__c ip = (Insurance_Policy__c)sc;
            Date today = Date.valueOf(system.now());
            if(ip.Expiration_Date__c < today){
                ip.Status__c = 'Terminated';
                ips.add(ip);
                policyIds.add(ip.Id);//Comment
            }
        }
        update ips;
    }
	public void finish(Database.BatchableContext BC){
       
        List<string> emailIds = new List<string>();
        If(!policyIds.isEmpty() && policyIds.size() > 0){
            List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
            List<Insurance_policy__c> ips = [select name, contact_email__c from insurance_policy__c where Id IN :policyIds];
            for(Insurance_policy__c ip : ips){
                emailIds.add(ip.contact_email__c);
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                mail.setToAddresses(new List<string>{ip.contact_email__c});
                mail.setSubject('Your Policy ' + ip.name + 'has be expired');
                mail.setPlainTextBody('Your Policy ' + ip.name + 'has be expired');
                mails.add(mail);
            }
			Messaging.sendEmail(mails);
        }
        
    }
}