force-app/main/default/objects/Insurance_Policy__c/Insurance_Policy__c.object-meta.xml
<CustomObject>
    <label>Insurance Policy</label>
    <nameField>
        <label>Insurance Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insurance Policies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insurance_Policy__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Insurance Policies</relationshipLabel>
    <relationshipName>Insurance_Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insurance_Policy__c/fields/Issuing_Date__c.field-meta.xml
<CustomField>
    <fullName>Issuing_Date__c</fullName>
    <label>Issuing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insurance_Policy__c/fields/Premium__c.field-meta.xml
<CustomField>
    <fullName>Premium__c</fullName>
    <label>Premium</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Insurance_Policy__c/fields/Premium_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Premium_Frequency__c</fullName>
    <label>Premium Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Policy__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Issued</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PolicyBulkUpdateTest.cls
@isTest
public with sharing class PolicyBulkUpdateTest {
    @isTest
    public static void testMethod1() {
        //Create Account
        Account accnt = new Account();
        accnt.Name = 'ABC Corp Ltd.';
        insert accnt;
        //Create Insurance Policy
        Insurance_policy__c ip = new Insurance_policy__c();
        ip.Name = '4000000570';
        ip.Effective_Date__c = Date.valueOf('2022-04-04');
        ip.Expiration_Date__c = Date.valueOf('2023-04-04');
        ip.Issuing_Date__c = Date.valueOf('2022-04-04');
        ip.Premium__c = 1000000;
        ip.Premium_Frequency__c = 'Yearly';
        ip.Status__c = 'Active';
        ip.contact_email__c = 'sujay.dey@salesforce.com';
        ip.Account__c = accnt.Id;
        insert ip;

        Test.startTest();
        PolicyBulkUpdate obj = new PolicyBulkUpdate();
        Database.executeBatch(obj, 100);
        test.stopTest();
    }
}